### ISSUE TITLE
Body Font-Family

### ISSUE THREAD

**Issue by semmons99** [mendicant-original/community#19]
When I visit http://community.mendicantuniversity.org/ in Chrome or IE on Windows 7, the font appear to be Times New Roman everywhere. I think this has to do with the `font-family` on `body`. When I inspect the element it's defined as

``` css
body {
  font-family: "helvetica, arial, freesans, clean, sans-serif"
}
```

When I remove the `"`'s everything looks much cleaner.
